### ISSUE TITLE
Titrer les images à l'import

### ISSUE THREAD

**Issue by jmoupah** [marcimat/bigup#2]
Par défaut, SPIP permet donner des titres à partir du nom du fichier pour les documents importés via ZIP (voir ci-dessous). 
Est-ce qu'il existe une possibilité dans Big up pour faire de même ?

![Clipboard01](https://user-images.githubusercontent.com/18148022/64108698-cb7bb900-cd7d-11e9-821a-9298125a904a.png)

**Comment by marcimat** [comment]
À part en utilisant la constante de configuration `define('_TITRER_DOCUMENTS', true);`, par exemple dans `config/mes_options.php` qui s’applique à tous les documents, il n’y a pas de moyen individuel fichier par fichier de le faire.

**Comment by jmoupah** [comment]
Ça marche, je note cette possibilité, merci.
C'est sûr qu'avec la direction prise pour la gestion des docs (disparition de la notion de portefolio...) ce fonctionnement historique n'a plus vraiment de raisons d'être...
