### ISSUE TITLE
Bigup pète tout autre drag&drop se trouvant sur la même page

### ISSUE THREAD

**Issue by rastapopougros** [marcimat/bigup#3]
Exemple : sur l'édition d'une sélection éditoriale.

D'après @marcimat c'est parce que @Cerdic a ajouté `onDropStopPropagation: true` :stuck_out_tongue:

**Comment by marcimat** [comment]
Alors rectifications déjà : le d&d de sélections éditoriales ne fonctionne déjà plus même sans BigUp. => range ta chambre :)

Cela dit, le problème reste : lorsque l’on définit les zones de d&d de BigUp, qui utilise Flow.js, cela appelle la fonction onDrop() de flow.js qui stoppe la propagation si l’option est activée, qu’on ait déposé des fichiers ou non dans la zone (https://github.com/marcimat/bigup/blob/master/lib/flow/flow.js#L130).

Du côté de BigUp, on déclare dans certains cas une zone de drop supplémentaire, très large, dont l’effet visuel est marqué au survol même si ce que l’on drag n’est pas un fichier. On pourrait peut être améliorer l’absence de visuel si on drop autre chose que des fichiers (https://github.com/marcimat/bigup/blob/master/javascript/bigup.js#L419) en reprenant le même principe que flow.js (tester event.dataTransfer.items et event.dataTransfer.files), mais flow.js interceptera toujours si on drop le contenu dans cette zone.

Peut être que l’on peut s’en sortir en redéclarant .assignDrop (.assignDropExtended) qui utiliserait l’évenement .onDropExtended (au lieu de .onDrop), qui sortirait s’il n’y a pas de fichier en continuant la propagation.

**Comment by marcimat** [comment]
J’ai tenté cette approche sans résultat concluant. 
Tant que le 'drop' n’est pas effectué, il ne semble pas y avoir de moyen de déterminer que le contenu du truc en 'drag' est un fichier.

**Comment by marcimat** [comment]
Finalement, c’est possible : https://stackoverflow.com/questions/25016442/how-to-distinguish-if-a-file-or-folder-is-being-dragged-prior-to-it-being-droppe

Ci joint une proposition de patch, qui évite qu’une sélection de texte active la zone de BigUp (visuellement). L’événement 'onDropExtended' est tout de même lancé si on dépose dans la zone prévue, mais normalement il ne se passe rien.

Ceci étant dit, je ne sais pas si c’est véritablement nécessaire de passer par tout cela (c’est fort probable que cela ajoute d’autres bugs) : effectivement même sans ça, le drag n drop de Sortable fonctionne sans activer BigUp (on le voit avec la liste des documents que l’on peut ordonner) ; 

```diff
diff --git a/javascript/bigup.js b/javascript/bigup.js
index f9e2a0e..21f7a03 100644
--- a/javascript/bigup.js
+++ b/javascript/bigup.js
@@ -230,6 +230,19 @@ function Bigup(params, opts, callbacks) {
 
        // Bigup accessible depuis l'input
        this.input.data('bigup', this);
+
+       /**
+        * On drop extended event
+        *
+        * On ne bloque pas la cascade des événements si on ne dépose pas de fichiers
+        * @function
+        * @param {MouseEvent} event
+        */
+       this.onDropExtended = function (event) {
+               if (me.eventHasFiles(event)) {
+                       me.flow.onDrop(event);
+               }
+       }
 }
 
 Bigup.prototype = {
@@ -384,7 +397,7 @@ Bigup.prototype = {
                        !this.multiple,
                        {accept: this.opts.contraintes.accept}
                );
-               this.flow.assignDrop(this.zones.depot_etendu);
+               this.assignDropExtended(this.zones.depot_etendu);
        },
 
        /**
@@ -415,10 +428,12 @@ Bigup.prototype = {
                                .add($zone_depot);
                }
 
-               var $c=this.class_name;
-               $depot_etendu.on('dragenter dragover', function(){
-                       $(this).addClass('drag-over');
-                       $zone_depot.addClass('drag-target');
+               var me = this;
+               $depot_etendu.on('dragenter dragover', function(event) {
+                       if (me.eventHasFiles(event.originalEvent)) {
+                               $(this).addClass('drag-over');
+                               $zone_depot.addClass('drag-target');
+                       }
                });
                $depot_etendu.on('dragleave', function(){
                        $(this).removeClass('drag-over');
@@ -787,6 +802,55 @@ Bigup.prototype = {
                        }
                });
                return data;
+       },
+
+
+       /**
+        * Assign one or more DOM nodes as a drop extended target.
+        * @function
+        * @param {Element|Array.<Element>} domNodes
+        */
+       assignDropExtended: function (domNodes) {
+               if (typeof domNodes.length === 'undefined') {
+                       domNodes = [domNodes];
+               }
+               Flow.each(domNodes, function (domNode) {
+                       domNode.addEventListener('dragover', this.flow.preventEvent, false);
+                       domNode.addEventListener('dragenter', this.flow.preventEvent, false);
+                       domNode.addEventListener('drop', this.onDropExtended, false);
+               }, this);
+       },
+
+       /**
+        * Un-assign drop extended event from DOM nodes
+        * @function
+        * @param domNodes
+        */
+       unAssignDrop: function (domNodes) {
+               if (typeof domNodes.length === 'undefined') {
+                       domNodes = [domNodes];
+               }
+               Flow.each(domNodes, function (domNode) {
+                       domNode.removeEventListener('dragover', this.flow.preventEvent);
+                       domNode.removeEventListener('dragenter', this.flow.preventEvent);
+                       domNode.removeEventListener('drop', this.onDropExtended);
+               }, this);
+       },
+
+       /**
+        * A drag event contain files ?
+        * @param MouseEvent event
+        * @return bool
+        */
+       eventHasFiles: function (event) {
+               if (event.dataTransfer.types) {
+                       for (var i = 0; i < event.dataTransfer.types.length; i++) {
+                               if (event.dataTransfer.types[i] === "Files") {
+                                       return true;
+                               }
+                       }
+               }
+               return false;
        }
 };
 

```

**Comment by rastapopougros** [comment]
Yep je vois ya plusieurs choses qui se sont accumulés sur les mêmes pages donc c'était confu. Charles a corrigé ce matin pour Sélections éditoriales, une classe qui avait été changée…

**Comment by jpyrat** [comment]
En lien avec https://core.spip.net/issues/4392

**Comment by marcimat** [comment]
J’ai intégré ce patch.
