### ISSUE TITLE
Intitulé du bouton « téléverser » confusionnant

### ISSUE THREAD

**Issue by tcharlss** [marcimat/bigup#4]
Ahoy,

Le formulaire d'upload est présenté de la sorte :
````
Téléverser
-------------------------
      [Téléverser]
          ou
Déposez vos fichiers ici
------------------------
````

Le bouton « téléverser » porte un peu à confusion : avant de téléverser des fichiers, mon 1er réflexe (par habitude ?) est de chercher un bouton pour les sélectionner.

Or là, le bouton sert à la fois à les sélectionner *et* à les téléverser ensuite, mais toujours est-il que je m'attends à faire la 1ère étape avant.

Ce serait peut-être plus clair avec quelque chose comme : « Choisir des fichiers » ou « Choisir les fichiers à téléverser » par exemple.

**Comment by tcharlss** [comment]
Nb : on a aussi 2 « téléverser » d'afilée du coup

**Comment by marcimat** [comment]
"Sélectionner" ou "Parcourir" pourrait convenir.
Mais Téléverser ne me choque pas vraiment.

**Comment by marcimat** [comment]
Va pour "Choisir".
