### ISSUE TITLE
Bug affichage si utilisation des constantes _IMG_MAX_XXX

### ISSUE THREAD

**Issue by akilia** [marcimat/bigup#9]
**Exemple (avec SPIP 3.3.0-dev SVN [24482])**
Dans mes_options, je défini deux constantes :
```
define('_IMG_MAX_WIDTH', 3000);
define('_IMG_MAX_HEIGHT', 1000);

```
…puis dans un article, je charge une image jpeg de 4000x5000 pixels.

**Résultat**
J'obtiens un affichage curieux avec une mini vignette en haut à gauche sur fond noir + une indication que l'image est en 4000x5000 pixels (voir copie écran ci-dessous)
![bug_bigup](https://user-images.githubusercontent.com/17119772/73613054-19793f00-45f2-11ea-9cdc-8940772d58aa.png)

En BdD et dans /IMG/logo/, tout est OK : j'ai bien une image resizé (800x1000).

**Note 1** :  Si je recharge la page, l'info sur la vignette devient exacte.
![bug_bigup2](https://user-images.githubusercontent.com/17119772/73613090-6b21c980-45f2-11ea-9da9-5adc3f18372e.png)

**Note 2** : si je vide /local/cache-vignettes, tout est bon.
![bug_bigup3](https://user-images.githubusercontent.com/17119772/73613115-b936cd00-45f2-11ea-87b0-646dc58b8a2f.png)

**Comment by marcimat** [comment]
Je n’ai pas l’impression que ça vienne de Bigup spécifiquement.
En le désactivant (l’enlever de plugins-dist/) j’obtiens le même résultat que toi.

**Comment by marcimat** [comment]
Ticket créé chez SPIP. https://core.spip.net/issues/4449

**Comment by akilia** [comment]
Ok. Merci de t'être occupé du ticket.
Cheers
